version: '3'
services:
 server1:
   build:
     dockerfile: Dockerfile
     context: ./server
   volumes:
    - /app/node_modules
    - ./server:/app
   environment: &environment
     - FROM=0
     - TO=50000 #latest #latest #0,1,latest, etc
     - RPC_URL=http://eth-lacchain.mytrust.id
   network_mode: host

 server2:
   build:
     dockerfile: Dockerfile
     context: ./server
   volumes:
    - /app/node_modules
    - ./server:/app
   environment: *environment
   network_mode: host

 server3:
   build:
     dockerfile: Dockerfile
     context: ./server
   volumes:
    - /app/node_modules
    - ./server:/app
   environment: *environment
   network_mode: host   

 server4:
   build:
     dockerfile: Dockerfile
     context: ./server
   volumes:
    - /app/node_modules
    - ./server:/app
   environment: *environment
   network_mode: host   


 server5:
   build:
     dockerfile: Dockerfile
     context: ./server
   volumes:
    - /app/node_modules
    - ./server:/app
   environment: *environment
   network_mode: host